import mysql.connector
from mysql.connector import Error

try:
    # MySQL 연결 설정
    connection = mysql.connector.connect(
        host='localhost',
        database='match5_data_set',
        user='root',
        password='@pas3$89+0D'
    )

    if connection.is_connected():
        cursor = connection.cursor()

        # 경기 길이와 참가자 id가 담긴 테이블
        create_parent_table_query = '''
        CREATE TABLE match (
            numbering INT(11) NOT NULL PRIMARY KEY,
            Duration INT(11),
            puuId1 VARCHAR(255),
            puuId2 VARCHAR(255),
            puuId3 VARCHAR(255),
            puuId4 VARCHAR(255),
            puuId5 VARCHAR(255),
            puuId6 VARCHAR(255),
            puuId7 VARCHAR(255),
            puuId8 VARCHAR(255),
            puuId9 VARCHAR(255),
            puuId10 VARCHAR(255),
        );
        '''

        # 경기 넘버, 길이 및 참가자 상세 정보 테이블
        create_match_participant = '''
        CREATE TABLE matchParticipant (
            numbering INT(11) NOT NULL,
            Duration INT(11),
            puuId VARCHAR(255) NOT NULL,
            allInPings INT(11),
            assistMePings INT(11),
            assists INT(11),
            baronKills INT(11),
            basicPings INT(11),
            bountyLevel INT(11),
            champExperience INT(11),
            champLevel INT(11),
            championId INT(11),
            championName VARCHAR(255),
            championTransform INT(11),
            commandPings INT(11),
            consumablesPurchased INT(11),
            damageDealtToBuildings INT(11),
            damageDealtToObjectives INT(11),
            damageDealtToTurrets INT(11),
            damageSelfMitigated INT(11),
            dangerPings INT(11),
            deaths INT(11),
            detectorWardsPlaced INT(11),
            doubleKills INT(11),
            dragonKills INT(11),
            eligibleForProgression BOOL,
            enemyMissingPings INT(11),
            enemyVisionPings INT(11),
            firstBloodAssist BOOL,
            firstBloodKill BOOL,
            firstTowerAssist BOOL,
            firstTowerKill BOOL,
            gameEndedInEarlySurrender BOOL,
            gameEndedInSurrender BOOL,
            getBackPings INT(11),
            goldEarned INT(11),
            goldSpent INT(11),
            holdPings INT(11),
            individualPosition VARCHAR(255),
            inhibitorKills INT(11),
            inhibitorTakedowns INT(11),
            inhibitorsLost INT(11),
            item0 INT(11),
            item1 INT(11),
            item2 INT(11),
            item3 INT(11),
            item4 INT(11),
            item5 INT(11),
            item6 INT(11),
            itemsPurchased INT(11),
            killingSprees INT(11),
            kills INT(11),
            lane VARCHAR(255),
            largestCriticalStrike INT(11),
            largestKillingSpree INT(11),
            largestMultiKill INT(11),
            longestTimeSpentLiving INT(11),
            magicDamageDealt INT(11),
            magicDamageDealtToChampions INT(11),
            magicDamageTaken INT(11),
            needVisionPings INT(11),
            neutralMinionsKilled INT(11),
            nexusKills INT(11),
            nexusLost INT(11),
            nexusTakedowns INT(11),
            objectivesStolen INT(11),
            objectivesStolenAssists INT(11),
            onMyWayPings INT(11),
            participantId INT(11),
            pentaKills INT(11),
            physicalDamageDealt INT(11),
            physicalDamageDealtToChampions INT(11),
            physicalDamageTaken INT(11),
            placement INT(11),
            playerAugment1 INT(11),
            playerAugment2 INT(11),
            playerAugment3 INT(11),
            playerAugment4 INT(11),
            playerAugment5 INT(11),
            playerAugment6 INT(11),
            playerSubteamId INT(11),
            profileIcon INT(11),
            pushPings INT(11),
            quadraKills INT(11),
            riotIdGameName VARCHAR(255),
            riotIdTagline VARCHAR(255),
            role VARCHAR(255),
            sightWardsBoughtInGame INT(11),
            spell1Casts INT(11),
            spell2Casts INT(11),
            spell3Casts INT(11),
            spell4Casts INT(11),
            subteamPlacement INT(11),
            summoner1Casts INT(11),
            summoner1Id INT(11),
            summoner2Casts INT(11),
            summoner2Id INT(11),
            summonerId VARCHAR(255),
            summonerLevel INT(11),
            summonerName VARCHAR(255),
            teamEarlySurrendered BOOL,
            teamId INT(11),
            teamPosition VARCHAR(255),
            timeCCingOthers INT(11),
            timePlayed INT(11),
            totalAllyJungleMinionsKilled INT(11),
            totalDamageDealt INT(11),
            totalDamageDealtToChampions INT(11),
            totalDamageShieldedOnTeammates INT(11),
            totalDamageTaken INT(11),
            totalEnemyJungleMinionsKilled INT(11),
            totalHeal INT(11),
            totalHealsOnTeammates INT(11),
            totalMinionsKilled INT(11),
            totalTimeCCDealt INT(11),
            totalTimeSpentDead INT(11),
            totalUnitsHealed INT(11),
            tripleKills INT(11),
            trueDamageDealt INT(11),
            trueDamageDealtToChampions INT(11),
            trueDamageTaken INT(11),
            turretKills INT(11),
            turretTakedowns INT(11),
            turretsLost INT(11),
            unrealKills INT(11),
            visionClearedPings INT(11),
            visionScore INT(11),
            visionWardsBoughtInGame INT(11),
            wardsKilled INT(11),
            wardsPlaced INT(11),
            win BOOL,
            playerScore0 INT(11),
            playerScore1 INT(11),
            playerScore2 INT(11),
            playerScore3 INT(11),
            playerScore4 INT(11),
            playerScore5 INT(11),
            playerScore6 INT(11),
            playerScore7 INT(11),
            playerScore8 INT(11),
            playerScore9 INT(11),
            playerScore10 INT(11),
            playerScore11 INT(11),
            baitPings INT(11),
            riotIdName VARCHAR(255),
            PRIMARY KEY (numbering, puuId)
        );
        '''

        # challenges
        create_challenges = '''
        CREATE TABLE challenges (
            numbering INT(11) NOT NULL,
            puuId VARCHAR(255) NOT NULL,
            12AssistStreakCount INT(11),
            InfernalScalePickup INT(11),
            SWARM_DefeatAatrox INT(11),
            SWARM_DefeatBriar INT(11),
            SWARM_DefeatMiniBosses INT(11),
            SWARM_EvolveWeapon INT(11),
            SWARM_Have3Passives INT(11),
            SWARM_KillEnemy INT(11),
            SWARM_PickupGold FLOAT,
            SWARM_ReachLevel50 INT(11),
            SWARM_Survive15Min INT(11),
            SWARM_WinWith5EvolvedWeapons INT(11),
            abilityUses INT(11),
            acesBefore15Minutes INT(11),
            alliedJungleMonsterKills FLOAT,
            baronTakedowns INT(11),
            blastConeOppositeOpponentCount INT(11),
            bountyGold INT(11),
            buffsStolen INT(11),
            completeSupportQuestInTime INT(11),
            controlWardTimeCoverageInRiverOrEnemyHalf FLOAT,
            controlWardsPlaced INT(11),
            damagePerMinute FLOAT,
            damageTakenOnTeamPercentage FLOAT,
            dancedWithRiftHerald INT(11),
            deathsByEnemyChamps INT(11),
            dodgeSkillShotsSmallWindow INT(11),
            doubleAces INT(11),
            dragonTakedowns INT(11),
            earlyLaningPhaseGoldExpAdvantage INT(11),
            effectiveHealAndShielding FLOAT,
            elderDragonKillsWithOpposingSoul INT(11),
            elderDragonMultikills INT(11),
            enemyChampionImmobilizations INT(11),
            enemyJungleMonsterKills FLOAT,
            epicMonsterKillsNearEnemyJungler INT(11),
            epicMonsterKillsWithin30SecondsOfSpawn INT(11),
            epicMonsterSteals INT(11),
            epicMonsterStolenWithoutSmite INT(11),
            firstTurretKilled INT(11),
            fistBumpParticipation INT(11),
            flawlessAces INT(11),
            fullTeamTakedown INT(11),
            gameLength FLOAT,
            getTakedownsInAllLanesEarlyJungleAsLaner INT(11),
            goldPerMinute FLOAT,
            hadOpenNexus INT(11),
            immobilizeAndKillWithAlly INT(11),
            initialBuffCount INT(11),
            initialCrabCount INT(11),
            jungleCsBefore10Minutes FLOAT,
            junglerTakedownsNearDamagedEpicMonster INT(11),
            kTurretsDestroyedBeforePlatesFall INT(11),
            kda FLOAT,
            killAfterHiddenWithAlly INT(11),
            killParticipation FLOAT,
            killedChampTookFullTeamDamageSurvived INT(11),
            killingSprees INT(11),
            killsNearEnemyTurret INT(11),
            killsOnOtherLanesEarlyJungleAsLaner INT(11),
            killsOnRecentlyHealedByAramPack INT(11),
            killsUnderOwnTurret INT(11),
            killsWithHelpFromEpicMonster INT(11),
            knockEnemyIntoTeamAndKill INT(11),
            landSkillShotsEarlyGame INT(11),
            laneMinionsFirst10Minutes INT(11),
            laningPhaseGoldExpAdvantage INT(11),
            legendaryCount INT(11),
            legendaryItemUsed VARCHAR(255),
            lostAnInhibitor INT(11),
            maxCsAdvantageOnLaneOpponent FLOAT,
            maxKillDeficit INT(11),
            maxLevelLeadLaneOpponent INT(11),
            mejaisFullStackInTime INT(11),
            moreEnemyJungleThanOpponent FLOAT,
            multiKillOneSpell INT(11),
            multiTurretRiftHeraldCount INT(11),
            multikills INT(11),
            multikillsAfterAggressiveFlash INT(11),
            outerTurretExecutesBefore10Minutes INT(11),
            outnumberedKills INT(11),
            outnumberedNexusKill INT(11),
            perfectDragonSoulsTaken INT(11),
            perfectGame INT(11),
            pickKillWithAlly INT(11),
            playedChampSelectPosition INT(11),
            poroExplosions INT(11),
            quickCleanse INT(11),
            quickFirstTurret INT(11),
            quickSoloKills INT(11),
            riftHeraldTakedowns INT(11),
            saveAllyFromDeath INT(11),
            scuttleCrabKills INT(11),
            skillshotsDodged INT(11),
            skillshotsHit INT(11),
            snowballsHit INT(11),
            soloBaronKills INT(11),
            soloKills INT(11),
            stealthWardsPlaced INT(11),
            survivedSingleDigitHpCount INT(11),
            survivedThreeImmobilizesInFight INT(11),
            takedownOnFirstTurret INT(11),
            takedowns INT(11),
            takedownsAfterGainingLevelAdvantage INT(11),
            takedownsBeforeJungleMinionSpawn INT(11),
            takedownsFirstXMinutes INT(11),
            takedownsInAlcove INT(11),
            takedownsInEnemyFountain INT(11),
            teamBaronKills INT(11),
            teamDamagePercentage FLOAT,
            teamElderDragonKills INT(11),
            teamRiftHeraldKills INT(11),
            tookLargeDamageSurvived INT(11),
            turretPlatesTaken INT(11),
            turretTakedowns INT(11),
            turretsTakenWithRiftHerald INT(11),
            twentyMinionsIn3SecondsCount INT(11),
            twoWardsOneSweeperCount INT(11),
            unseenRecalls INT(11),
            visionScoreAdvantageLaneOpponent FLOAT,
            visionScorePerMinute FLOAT,
            voidMonsterKill INT(11),
            wardTakedowns INT(11),
            wardTakedownsBefore20M INT(11),
            wardsGuarded INT(11),
            junglerKillsEarlyJungle INT(11),
            killsOnLanersEarlyJungleAsJungler INT(11),
            teleportTakedowns INT(11),
            firstTurretKilledTime FLOAT,
            shortestTimeToAceFromFirstTakedown FLOAT,
            soloTurretsLategame INT(11),
            earliestDragonTakedown FLOAT,
            fastestLegendary FLOAT,
            highestChampionDamage INT(11),
            highestWardKills INT(11),
            highestCrowdControlScore INT(11),
            fasterSupportQuestCompletion INT(11),
            hadAfkTeammate INT(11),
            earliestBaron FLOAT,
            baronBuffGoldAdvantageOverThreshold INT(11),
            thirdInhibitorDestroyedTime FLOAT,
            HealFromMapSources FLOAT,
            earliestElderDragon FLOAT,
            mythicItemUsed INT(11),
            threeWardsOneSweeperCount INT(11),
            PRIMARY KEY (numbering, puuId),
            FOREIGN KEY (numbering, puuId) REFERENCES matchParticipant(numbering, puuId)
        );
        '''

        # missions
        create_missions = '''
        CREATE TABLE missions (
            numbering INT(11) NOT NULL,
            puuId VARCHAR(255) NOT NULL,
            playerScore0 INT(11),
            playerScore1 INT(11),
            playerScore2 INT(11),
            playerScore3 INT(11),
            playerScore4 INT(11),
            playerScore5 INT(11),
            playerScore6 INT(11),
            playerScore7 INT(11),
            playerScore8 INT(11),
            playerScore9 INT(11),
            playerScore10 INT(11),
            playerScore11 INT(11),
            PRIMARY KEY (numbering, puuId),
            FOREIGN KEY (numbering, puuId) REFERENCES matchParticipant(numbering, puuId)
        );
        '''

        # perkStats
        create_perkStats = '''
        CREATE TABLE perkStats (
            numbering INT(11) NOT NULL,
            puuId VARCHAR(255) NOT NULL,
            defense INT(11),
            flex INT(11),
            offense INT(11),
            PRIMARY KEY (numbering, puuId),
            FOREIGN KEY (numbering, puuId) REFERENCES matchParticipant(numbering, puuId)
        );
        '''

        # perkStyle
        create_perkStyle = '''
        CREATE TABLE perkStyle (
            numbering INT(11) NOT NULL,
            puuId VARCHAR(255) NOT NULL,
            primary_style INT(11),
            sub_style INT(11),
            primary_perk1 INT(11),
            primary_perk1_value1 INT(11),
            primary_perk1_value2 INT(11),
            primary_perk1_value3 INT(11),
            primary_perk2 INT(11),
            primary_perk2_value1 INT(11),
            primary_perk2_value2 INT(11),
            primary_perk2_value3 INT(11),
            primary_perk3 INT(11),
            primary_perk3_value1 INT(11),
            primary_perk3_value2 INT(11),
            primary_perk3_value3 INT(11),
            primary_perk4 INT(11),
            primary_perk4_value1 INT(11),
            primary_perk4_value2 INT(11),
            primary_perk4_value3 INT(11),
            sub_perk1 INT(11),
            sub_perk1_value1 INT(11),
            sub_perk1_value2 INT(11),
            sub_perk1_value3 INT(11),
            sub_perk2 INT(11),
            sub_perk2_value1 INT(11),
            sub_perk2_value2 INT(11),
            sub_perk2_value3 INT(11),
            PRIMARY KEY (numbering, puuId, description)
        );
        '''

        # matchParticipan
        cursor.execute(create_match_participant)
        print("테이블 [matchParticipant] 생성 완료")

        # challenges
        cursor.execute(create_challenges)
        print("테이블 [challenges] 생성 완료")

        # missions
        cursor.execute(create_missions)
        print("테이블 [missions] 생성 완료")

        # perkStats
        cursor.execute(create_perkStats)
        print("테이블 [perkStats] 생성 완료")

        # perkStyle
        cursor.execute(create_perkStyle)
        print("테이블 [perkStyle] 생성 완료")

        # 변경사항 저장
        connection.commit()

except Error as e:
    print(f"Error: {e}")

finally:
    # 연결 해제
    if connection.is_connected():
        cursor.close()
        connection.close()
        print("mysql 종료!")
